version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=catsdogs123
      - POSTGRES_DB=postgres
  scraper:
    build: ./Scraper
    environment:
      DATABASE_URL: postgresql://postgres:catsdogs123@localhost:5432/postgres?schema=public
  frontend:
    build: ./apartments-ads
    ports:
      - 3000:3000
  backend:
    build: ./api-server
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:catsdogs123@localhost:5432/postgres?schema=public

volumes:
  pgdata:
